---
# /etc/openstack_deploy/conf.d/cinder.yml
storage-infra_hosts:
  infra01:
    ip: 172.29.176.101
  infra02:
    ip: 172.29.176.102
  infra03:
    ip: 172.29.176.103

storage_hosts:
  cinder01:
    ip: 172.29.176.130
    container_vars:
      cinder_storage_availability_zone: nova
      cinder_default_availability_zone: nova
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: 172.29.176.130
  cinder02:
    ip: 172.29.176.131
    container_vars:
      cinder_storage_availability_zone: nova
      cinder_default_availability_zone: nova
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: 172.29.176.131
  cinder03:
    ip: 172.29.176.132
    container_vars:
      cinder_storage_availability_zone: nova
      cinder_default_availability_zone: nova
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: 172.29.176.132
