---
# /etc/openstack_deploy/conf.d/cinder.yml
storage-infra_hosts:
  infra01:
    ip: 172.29.176.30
  infra02:
    ip: 172.29.176.31
  infra03:
    ip: 172.29.176.32

storage_hosts:
  cinder01:
    ip: 172.29.176.60
    container_vars:
      cinder_storage_availability_zone: nova
      cinder_default_availability_zone: nova
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: 172.29.176.60
  cinder02:
    ip: 172.29.176.61
    container_vars:
      cinder_storage_availability_zone: nova
      cinder_default_availability_zone: nova
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: 172.29.176.61
  cinder03:
    ip: 172.29.176.62
    container_vars:
      cinder_storage_availability_zone: nova
      cinder_default_availability_zone: nova
      cinder_backends:
        limit_container_types: cinder_volume
        lvm:
          volume_group: cinder-volumes
          volume_driver: cinder.volume.drivers.lvm.LVMVolumeDriver
          volume_backend_name: LVM_iSCSI
          iscsi_ip_address: 172.29.176.62
