---
# The infra nodes that will be running the magnum services
# /etc/openstack_deploy/conf.d/magnum.yml
magnum-infra_hosts:
  infra01:
    ip: 172.29.176.101
  infra02:
    ip: 172.29.176.102
  infra03:
    ip: 172.29.176.103