---
# /etc/openstack_deploy/openstack_user_config.yml
cidr_networks:
  container: 172.29.176.0/22
  tunnel: 172.29.180.0/22
  storage: 172.29.184.0/22
  snet: 172.29.188.0/22

used_ips:
  - 172.29.176.1,172.29.176.254
  - 172.29.180.1,172.29.180.254
  - 172.29.184.1,172.29.184.254
  - 172.29.188.1,172.29.188.254

global_overrides:
  internal_lb_vip_address: 172.29.176.100
  external_lb_vip_address: 192.168.0.249
  management_bridge: "br-mgmt"
  tunnel_bridge: "br-vxlan"
  provider_networks:
    - network:
        group_binds:
          - all_containers
          - hosts
        type: "raw"
        container_bridge: "br-mgmt"
        container_interface: "eth1"
        container_type: "veth"
        ip_from_q: "container"
        is_container_address: true
        is_ssh_address: true
    - network:
        group_binds:
          - glance_api
          - cinder_api
          - cinder_volume
          - nova_compute
          # Uncomment the next line if using ceph
          # - mons
          # Uncomment the next line if using swift with a storage network.
          - swift_proxy
        type: "raw"
        container_bridge: "br-storage"
        container_type: "veth"
        container_interface: "eth2"
        container_mtu: "9000"
        ip_from_q: "storage"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vxlan"
        container_type: "veth"
        container_interface: "eth10"
        container_mtu: "9000"
        ip_from_q: "tunnel"
        type: "vxlan"
        range: "1:1000"
        net_name: "vxlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-vlan"
        container_type: "veth"
        container_interface: "eth11"
        type: "vlan"
        range: "205:209"
        net_name: "vlan"
    - network:
        group_binds:
          - neutron_linuxbridge_agent
        container_bridge: "br-flat"
        container_type: "veth"
        container_interface: "eth12"
        type: "flat"
        net_name: "flat"
    - network:
        group_binds:
          - glance_api
          - nova_compute
          - neutron_linuxbridge_agent
        type: "raw"
        container_bridge: "br-snet"
        container_type: "veth"
        container_interface: "eth3"
        ip_from_q: "snet"

shared-infra_hosts:
  infra01:
    ip: 172.29.176.101
  infra02:
    ip: 172.29.176.102
  infra03:
    ip: 172.29.176.103

repo-infra_hosts:
  infra01:
    ip: 172.29.176.101
  infra02:
    ip: 172.29.176.102
  infra03:
    ip: 172.29.176.103

os-infra_hosts:
  infra01:
    ip: 172.29.176.101
  infra02:
    ip: 172.29.176.102
  infra03:
    ip: 172.29.176.103
