---
- name: Post OpenStack Installation Defaults
  become: yes
  remote_user: root
  hosts: localhost

  tasks:
    - name: Install python-openstackclient

    - name: Get cloud images

    - name: Import images into Glance

    - name: Create security group

    - name: Create key-pair

    - name: Create five floating IPs

    - name: Create an instance

    - name: Create block storage

    - name: Create object storage

    - name: Attach block storage to instance

- name: Setup OpenStack Network
  become: yes
  remote_user: root
  hosts: localhost

  tasks:
    - name: Get OpenStack Credentials

    - name: Source OpenStack Credentials

    - name: Create External Network

    - name: Create External Network Subnet

    - name: Create Internal Network

    - name: Create Internal Network Subnet

    - name: Create External Router

    - name: Set Router Gateway to External Network

    - name: Add Internal Network to Router
